### ISSUE TITLE
Not easy enough to setup peers

### ISSUE THREAD

**Issue by Perflyst** [notabugio-archived/notabug-ui#19]
I tried following this guide: https://notabug.io/help/knownpeers

But it is not possible to start notabug with forever as peer-configs are missing.
Also this link https://github.com/notabugio/notabug/tree/master/peer-configs is broken

**Comment by go1dfish** [comment]
Forever isn't used anymore and I should update the instructions

pm2 is used now.

    cp server-config.json.example server-config.json
    yarn && yarn build
    yarn uidev

That will give you a lmdb backed peer that mirrors content as it appears on the network and will sync old content as you view it, as well as automatically rebuilding the ui as you change it for dev purposes.


yarn start will start up a similar setup without the dev rebuilding.

https://github.com/notabugio/notabug/blob/master/package.json#L17 has a collection of commands used.


If you want to run an indexer it's a bit more complicated, modify server-config.json for your account and ui-config.json to change the indexer to your public key, then yarn build and yarn start.


Haven't documented this out well yet because synchronization of old content is not yet well solved; but this is only an issue if you are interested in running an indexer.

Also, next time you make a github issue drop a link on notabug.io and I'll see it faster.

**Comment by go1dfish** [comment]
It's now possible to start up a mirroring peer with a single docker command.

https://github.com/notabugio/notabug#docker-usage

Still need to do some work to make indexers easier to setup and deal with old content synchronization.  Also I want to move away from ui-config.json in favor of environment variables for defining indexer/tabulator/owner  but for a mirroring peer or ui development these concerns don't matter much.
